version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  redis:
    image: redis
    volumes:
      - ./backend/tmp/redis:/data
    ports:
      - 6379:6379
  worker:
    build: ./backend
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./backend:/backend
    depends_on:
      - db
      - redis
  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/backend
    environment:
      POSTGRES_USERNAME:    postgres
      POSTGRES_PASSWORD:    password
      COMPANY_API_URL:      https://fakerapi.it/api/v1/companies
      COMPANY_API_SEED:     1
      COMPANY_API_QUANTITY: 200
      REDIS_URL:            redis://redis:6379/0
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - worker
  nginx:
    image: bitnami/nginx:1.10.2-r1
    volumes:
      - ./config/nginx:/bitnami/nginx/conf/vhosts
    depends_on:
      - backend
    environment:
      VIRTUAL_HOST: dealer.docker
      VIRTUAL_PORT: 8080
    ports:
      - 8080:8080
